### ISSUE TITLE
Feature: condition on event

### ISSUE THREAD

**Issue by thomakl** [juliencegarra/OpenMATB#21]
Hi,

I would like to create a scenario with a conditional event such as : 
`IF (sysmon,light1,on AND sysmon,light2,on): THEN{track:automaticsolver:off}`

Do you think it can be done ?
Cheers,

**Comment by benoitvalery** [comment]
Hi @thomakl,
I close this issue since this is not the philosophy of OpenMATB which is, for now, to implement deterministic scenarios. The best way is to do things manually:

```
0:00:05;sysmon;lights-1-on;true
0:00:05;sysmon;lights-2-on;true
0:00:05;sysmon;automaticsolver;off
```

You can also think about a scenario generator which could handle the conditioning, and output predetermined scenario, as needed by the MATB philosophy.
