### ISSUE TITLE
Eyetracker parameters

### ISSUE THREAD

**Issue by gauravspatil** [juliencegarra/OpenMATB#37]
I'm setting up an experiment using the OpenMATB library and noticed that you have the eyetracker.py code included in plugins but no documentaion is provided about its usage. Nor is it mentioned in the parameters.csv.

Can you provide more details about how it is used? I have access to the "SR Research EyeLink Portable Duo" and I am currently exploring ways on how to best record eye data with OpenMATB.

Thanks for all of your work!

**Comment by benoitvalery** [comment]
Hi @gauravspatil, thanks for your interest.
The `eyetracker.py` is yet some kind of dummy coding, which is not really functional.

For now, the best way to record and synchronize your ET data with OpenMATB is to use the lab streaming layer method (LSL), which is implemented into OpenMATB.

If you do not know at all about LSL, I recommend that you take some time to read some introduction to it (e.g., https://labstreaminglayer.org/#/). Then, the way is not that complicated.

1. On the OpenMATB side, you will have to enable LSL, using the `labstreaminglayer.py` plugin, so that all the OpenMATB information (the log content) will be streamed over the network, on a particular outlet.
2. Retrieve and use the LSL binary for your particular ET device (Look at [this google research](https://www.google.com/search?client=firefox-b-e&q=LSL+EyeLink) to begin with.), so the data recorded will be also streamed over the network.
3. You must also have a computer dedicated to listen the network and record those particular streams that you are interested in.

The general principle is that your streams will be synchronized by the network itself. This is a very general explanation. Let me know if you need more support (though I’m not an LSL expert).
